### ISSUE TITLE
error when running python control.py

### ISSUE THREAD

**Issue by yani-rl-ai** [lobachevzky/hsr-env#1]
Hi @ethanabrooks, i am interested with your project. 
right now i am a beginner in python and mujoco.
when i run python control.py i got this following error :

(mujocogym) kubotalab@kubotalab:~/hsr-env/hsr$ python hsr/control.py --block-space (0,0)(0,0)(0,0)(0,0) --steps-per-action=300 --geofence=.5 --goal-space (0,0)(0,0)(0,0)
bash: syntax error near unexpected token `('

please kindly help me

**Comment by yani-rl-ai** [comment]
hi @oidelima can you help my problem? i am very interested in your project. i am new in python and mujoco

**Comment by yani-rl-ai** [comment]
hi @ethanabrooks  can you help me?

**Comment by ethanabrooks** [comment]
Hi ROSNovice. You would need to put quotes around the argument to `--block-space` and `--goal-space`:
```bash
(mujocogym) kubotalab@kubotalab:~/hsr-env/hsr$ python hsr/control.py --block-space '(0,0)(0,0)(0,0)(0,0)' --steps-per-action=300 --geofence=.5 --goal-space '(0,0)(0,0)(0,0)'
```

**Comment by yani-rl-ai** [comment]
Hi @ethanabrooks thanks for your reply. i can run the simulation, but the robot keep
